FROM ubuntu:14.04　

MAINTAINER dev

RUN apt-get update && apt-get install -y wget vim git sudo net-tools python-apt libssl-dev libreadline6-dev tk-dev openssh-server apache2 software-properties-common python-software-properties

# Create user
RUN useradd dev
#RUN echo "dev:dev" | chpasswd
#RUN usermod -G sudo dev
#RUN echo "dev   ALL=(ALL)       ALL" >> /etc/sudoers

# Set up SSH
RUN mkdir -p /home/dev/.ssh; chown dev:dev /home/dev; chown dev:dev /home/dev/.ssh; chmod 700 /home/dev/.ssh
RUN touch /home/dev/.ssh/authorized_keys
RUN ssh-keygen -f /home/dev/.ssh/dpub_front-dev
RUN cat /home/dev/.ssh/dpub_front-dev.pub >> /home/dev/.ssh/authorized_keys
RUN echo /home/dev/.ssh/dpub_front-dev

RUN chown dev:dev /home/dev/.ssh/authorized_keys
RUN chown dev:dev /home/dev/.ssh/dpub_front-dev.pub
RUN chown dev:dev /home/dev/.ssh/dpub_front-dev
RUN chmod 600 /home/dev/.ssh/authorized_keys

#
RUN mkdir /var/run/sshd

